formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  # Azure Security - Network Security Group

  This Terraform module creates and manages Azure Network Security Groups (NSGs) with configurable security rules, associations, and advanced features like flow logging.

  ## Features

  - **Comprehensive NSG Management**: Create and configure Network Security Groups with custom security rules
  - **Flexible Rule Configuration**: Support for both simple and complex security rule definitions
  - **Multiple Association Types**: Associate NSGs with subnets or network interfaces
  - **Resource Group Management**: Optionally create or use existing resource groups
  - **Flow Logging Support**: Configure flow logs for network traffic analysis
  - **Tag Management**: Comprehensive tagging with common and resource-specific tags
  - **Validation**: Extensive input validation for all parameters
  - **Enterprise Standards**: Follows ZRR enterprise standards and best practices

  ## Usage

  ### Basic Example

  ```hcl
  module "network_security_group" {
    source = "../../azure/security/network-security-group"

    name                = "example-nsg"
    location            = "East US"
    resource_group_name = "example-rg"

    security_rules = [
      {
        name                       = "allow-ssh"
        priority                   = 1001
        direction                  = "Inbound"
        access                     = "Allow"
        protocol                   = "Tcp"
        source_port_range          = "*"
        destination_port_range     = "22"
        source_address_prefix      = "*"
        destination_address_prefix = "*"
        description                = "Allow SSH access"
      }
    ]

    common_tags = {
      Environment = "dev"
      Project     = "example"
    }
  }
  ```

  ### Advanced Example with Flow Logs

  ```hcl
  module "advanced_nsg" {
    source = "../../azure/security/network-security-group"

    name                = "advanced-nsg"
    location            = "East US"
    resource_group_name = "example-rg"

    security_rules = [
      {
        name                         = "allow-http-https"
        priority                     = 1000
        direction                    = "Inbound"
        access                       = "Allow"
        protocol                     = "Tcp"
        source_port_range            = "*"
        destination_port_ranges      = ["80", "443"]
        source_address_prefix        = "*"
        destination_address_prefix   = "*"
        description                  = "Allow HTTP and HTTPS traffic"
      },
      {
        name                         = "deny-all-inbound"
        priority                     = 4000
        direction                    = "Inbound"
        access                       = "Deny"
        protocol                     = "*"
        source_port_range            = "*"
        destination_port_range       = "*"
        source_address_prefix        = "*"
        destination_address_prefix   = "*"
        description                  = "Deny all other inbound traffic"
      }
    ]

    enable_flow_logs              = true
    flow_log_storage_account_id   = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx"
    flow_log_retention_days       = 90

    subnet_id = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx"

    common_tags = {
      Environment = "production"
      Project     = "webapp"
      Owner       = "security-team"
    }

    network_security_group_tags = {
      Purpose = "web-tier"
      Backup  = "daily"
    }
  }
  ```

  ## Security Rules

  Security rules support the following configuration options:

  - **Priority**: Must be between 100-4096 (lower numbers have higher priority)
  - **Direction**: Inbound or Outbound
  - **Access**: Allow or Deny
  - **Protocol**: Tcp, Udp, Icmp, Esp, Ah, or * (any)
  - **Port Ranges**: Single port, port range, or list of ports
  - **Address Prefixes**: IP addresses, CIDR blocks, or service tags

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true